### ISSUE TITLE
[PE-D][Tester C] Command Summary does not have SETCRS in it

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-1/tp#191] opened 2024-04-05 19:44 UTC
![image.png](https://raw.githubusercontent.com/eliotlee68/ped/main/files/c9670a97-99c4-4999-9823-81337f011961.png)

The command summary in the user guide is not updated with the SETCRS function

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: eliotlee68/ped#6

**Comment by tituschewxj** [comment] 2024-04-06 10:17
Duplicate of #202

**Closed** 2024-04-06 10:24 UTC
