### ISSUE TITLE
[PE-D][Tester A] Autocorrect suggests placeholder values for email

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-1/tp#219] opened 2024-04-05 22:17 UTC
![image.png](https://raw.githubusercontent.com/LWS49/ped/main/files/49b3e07b-a873-4f9f-8d7d-fb0f1537bfab.png)
Autocorrect can produce "Email not provided" for email by typing "find e/", followed by Tab.

Autocomplete can produce "Email not provided" as long as the string provided spells out the characters in order (E, Em, Ema etc, all produces it).

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LWS49/ped#21

**Comment by tituschewxj** [comment] 2024-04-06 01:47
Note: this is intended behaviour, as it is the only way to clear the field, without deleting and recreating the person. It is accepted as an input when entered. We need to document this behaviour in the user guide.

**Comment by tituschewxj** [comment] 2024-04-07 13:40
Duplicate of #221

**Closed by tituschewxj** 2024-04-07 13:40 UTC
