### ISSUE TITLE
[PE-D][Tester D] User Guide Bug: examples for addstu does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-1/tp#210] opened 2024-04-05 22:00 UTC
The first two examples given are not working when typed into the application.

I feel that that the team should include working examples so that the user will have a guide when they are unsure on how the commands work.

![image.png](https://raw.githubusercontent.com/guohuang88/ped/main/files/4f730830-240c-4206-a998-e2f1ad559fbe.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: guohuang88/ped#10

**Comment by tituschewxj** [comment] 2024-04-07 13:55
Duplicate of #232

**Closed by tituschewxj** 2024-04-07 13:55 UTC
