### ISSUE TITLE
[PE-D][Tester D] User Guide Bug: Not enough screenshots

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-1/tp#209] opened 2024-04-05 21:54 UTC
There are many features without a screenshot and there are a lot of blank space.

Screenshot can be good as it allows the user to know what to expect when a feature is executed.

![image.png](https://raw.githubusercontent.com/guohuang88/ped/main/files/e78667b0-7279-49c0-b3a3-eee23437e707.png)

![image.png](https://raw.githubusercontent.com/guohuang88/ped/main/files/40a0c60a-923b-4310-851b-6d9842b0fef4.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: guohuang88/ped#9

**Comment by tituschewxj** [comment] 2024-04-07 14:56
Duplicate of #158

**Closed by tituschewxj** 2024-04-07 14:56 UTC
Labels: type.ug, canfix
